In [15]:
import matplotlib as pyplot
import pandas as pd

In [19]:
df=pd.read_csv('../data301-proj1/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.csv')

In [20]:
df= df.drop('Currency - other', axis=1)
df= df.drop('Additional context on job title', axis=1)
df= df.drop('Additional context on income', axis=1)

In [25]:
df

,Timestamp,How old are you?,Industry,Job title,Annual salary,Other monetary comp,Currency,Country,State,City,Overall years of professional experience,Years of experience in field,Highest level of education completed,Gender,Race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,"55,000",0.0,USD,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,"54,600",4000.0,GBP,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,"34,000",NaN,USD,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,"62,000",3000.0,USD,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,"60,000",7000.0,USD,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27604,1/8/2022 14:37:49,25-34,Retail,Training and Development Coordinator,41600,2000.0,USD,United States,Kentucky,Louisville,5-7 years,2 - 4 years,College degree,Woman,White
27605,1/8/2022 18:13:03,25-34,Computing or Tech,contract manager,80000,6000.0,CAD,canada,NaN,toronto,1 year or less,1 year or less,Master's degree,Woman,White
27606,1/9/2022 12:04:28,25-34,Transport or Logistics,RPA Developer,75000,0.0,USD,USA,Texas,Houston,2 - 4 years,2 - 4 years,College degree,Man,"Hispanic, Latino, or Spanish origin"
27607,1/9/2022 22:49:35,25-34,Computing or Tech,IT Specialist,45760,0.0,USD,USA,Wisconsin,Oconomowoc,5-7 years,2 - 4 years,College degree,Man,Asian or Asian American
27608,1/11/2022 13:26:41,55-64,Education (Higher Education),instructor,80000,0.0,USD,usa,Virginia,hampton,31 - 40 years,8 - 10 years,Master's degree,Man,White

In [22]:
df = df.drop(26562)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27608 entries, 0 to 27608
Data columns (total 15 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Timestamp                                 27608 non-null  object
 1   How old are you?                          27608 non-null  object
 2   Industry                                  27539 non-null  object
 3   Job title                                 27608 non-null  object
 4   Annual salary                             27608 non-null  object
 5   Other monetary comp                       20462 non-null  float64
 6   Currency                                  27608 non-null  object
 7   Country                                   27608 non-null  object
 8   State                                     22697 non-null  object
 9   City                                      27530 non-null  object
 10  Overall years of professional experience  27608 non-null  object
 11  Years of experience in field              27608 non-null  object
 12  Highest level of education completed      27401 non-null  object
 13  Gender                                    27444 non-null  object
 14  Race                                      27448 non-null  object
dtypes: float64(1), object(14)
memory usage: 3.4+ MB

In [24]:
df.isna().any() #pushes out any Nan's in a column

Timestamp                                   False
How old are you?                            False
Industry                                     True
Job title                                   False
Annual salary                               False
Other monetary comp                          True
Currency                                    False
Country                                     False
State                                        True
City                                         True
Overall years of professional experience    False
Years of experience in field                False
Highest level of education completed         True
Gender                                       True
Race                                         True
dtype: bool

In [ ]:
df.drop

In [13]:
df

,Timestamp,How old are you?,Industry,Job title,Additional context on job title,Annual salary,Other monetary comp,Currency,Additional context on income,Country,State,City,Overall years of professional experience,Years of experience in field,Highest level of education completed,Gender,Race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27604,1/8/2022 14:37:49,25-34,Retail,Training and Development Coordinator,NaN,41600,2000.0,USD,NaN,United States,Kentucky,Louisville,5-7 years,2 - 4 years,College degree,Woman,White
27605,1/8/2022 18:13:03,25-34,Computing or Tech,contract manager,NaN,80000,6000.0,CAD,NaN,canada,NaN,toronto,1 year or less,1 year or less,Master's degree,Woman,White
27606,1/9/2022 12:04:28,25-34,Transport or Logistics,RPA Developer,NaN,75000,0.0,USD,NaN,USA,Texas,Houston,2 - 4 years,2 - 4 years,College degree,Man,"Hispanic, Latino, or Spanish origin"
27607,1/9/2022 22:49:35,25-34,Computing or Tech,IT Specialist,Desktop Support/Healp Desk,45760,0.0,USD,NaN,USA,Wisconsin,Oconomowoc,5-7 years,2 - 4 years,College degree,Man,Asian or Asian American
27608,1/11/2022 13:26:41,55-64,Education (Higher Education),instructor,NaN,80000,0.0,USD,NaN,usa,Virginia,hampton,31 - 40 years,8 - 10 years,Master's degree,Man,White